# Generated by Django 5.0.1 on 2024-02-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0005_video_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='likes',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='views',
            new_name='view',
        ),
        migrations.RemoveField(
            model_name='video',
            name='icon',
        ),
    ]
