# Generated by Django 5.0.1 on 2024-03-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dd_app", "0006_rename_likes_video_like_rename_tags_video_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="thumbnails/"),
        ),
    ]
