# Generated by Django 5.0.1 on 2024-02-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
